=== aws3ma/xml/TP/TP1/ex1/Ex11.dtd
<!ELEMENT stock (bouteille+)>
<!ELEMENT bouteille ((marque,composition,source,code_barre,contenance,ph) | (marque,source,volume,composition))>
<!ATTLIST bouteille pH NMTOKEN #IMPLIED>
<!ATTLIST bouteille code NMTOKEN #IMPLIED>
<!ELEMENT volume (#PCDATA)>
<!ATTLIST volume unite NMTOKEN #IMPLIED>
<!ELEMENT marque (#PCDATA)>
<!ELEMENT composition (ion+,autre?)>
<!ELEMENT ion (#PCDATA)>
<!ATTLIST ion type (negatif|positif) #IMPLIED>
<!ATTLIST ion tpye NMTOKEN #IMPLIED>
<!ATTLIST ion unite CDATA #FIXED "mg/l">
<!ELEMENT autre (#PCDATA)>
<!ATTLIST autre type NMTOKEN #IMPLIED>
<!ELEMENT source (ville?,departement?)>
<!ATTLIST source region CDATA #IMPLIED>
<!ATTLIST source ville CDATA #IMPLIED>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT departement (#PCDATA)>
<!ELEMENT code_barre (#PCDATA)>
<!ELEMENT contenance (#PCDATA)>
<!ATTLIST contenance unit NMTOKEN #REQUIRED>
<!ELEMENT ph (#PCDATA)>

=== aws3ma/xml/TP/TP1/ex1/ex1.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stock SYSTEM "Ex11.dtd">
<stock>
    <bouteille pH="7.45" code="6274080005003">
        <marque>Fourat</marque>
        <source region="Ksar Lemsa" ville=" Kairouan " />
        <volume unite="cl">15O</volume>
        <composition>
            <ion type="positif" unite="mg/l">Calcium:71,Magnesium:5,5</ion>
            <ion type="negatif" unite="mg/l">Chlorure: 20.nitrates:1</ion>
            <autre> Fer</autre>
        </composition>
    </bouteille>
    <bouteille pH="7" code="6266845671118">
        <marque>Sabrine</marque>
        <source region="Mizeb" ville="Gasrine" />
        <volume unite="cl">50</volume>
        <composition>
            <ion type="positif" unite="mg/l">Calcium:98. Magnesium:44</ion>
            <ion type="negatif" unite="mg/l">Chlorure: 3,6,nitrates/2</ion>
        </composition>
    </bouteille>
    <bouteille pH="7" code="6058632517118">
        <marque> Maxwa </marque>
        <source region="Kef Ghrab" ville="Bizertz" />
        <volume unite="cl">50</volume>
        <composition>
            <ion type="positif" unite="mg/l">Calcium: 11,5 ,Magnesium:8</ion>
            <ion type="negatif" unite="mg/l">Chlorure: 13,5 ,nitrates/6,3</ion>
            <autre> Silice</autre>
        </composition>
    </bouteille>
</stock>
